refactor: 开发/构建流程优化
realsee-developer/dnalogel pull request #124
Opened 2022-11-10 12:40 UTC by sansi-lcj

2022-11-11 03:55 UTC, Emiyaaaaa requested changes

2022-11-11 03:55 UTC, Emiyaaaaa commented on plugins/vite.config.js
> +          plugins: [cp({ targets: [{ src: 'dist/index.es.js', dest: 'dist', rename: 'index.js' }] })],
之前好像是把index.cjs.js改的index.js，我那版改错了

2022-11-11 03:55 UTC, Emiyaaaaa commented on plugins/vite.config.js
> +              formats: ['es'],
之前也是打的cjs包

2022-11-11 03:55 UTC, Emiyaaaaa commented on plugins/vite.config.js
> +              formats: ['es'],
https://github.com/realsee-developer/dnalogel/blob/9031a316477296f290efd9d34a7986b3885669a1/plugins/rollup.config.js

2022-11-11 03:55 UTC, Emiyaaaaa commented on plugins/vite.config.js
> +          plugins: [cp({ targets: [{ src: 'dist/index.es.js', dest: 'dist', rename: 'index.js' }] })],
https://github.com/realsee-developer/dnalogel/blob/9031a316477296f290efd9d34a7986b3885669a1/plugins/rollup.config.js

2022-11-14 03:46 UTC, Arrrrray approved these changes

2022-11-15 02:53 UTC, sansi-lcj commented on plugins/vite.config.js
> +          plugins: [cp({ targets: [{ src: 'dist/index.es.js', dest: 'dist', rename: 'index.js' }] })],
已处理

2022-11-15 02:53 UTC, sansi-lcj commented on plugins/vite.config.js
> +          plugins: [cp({ targets: [{ src: 'dist/index.es.js', dest: 'dist', rename: 'index.js' }] })],
已处理

2022-11-15 03:49 UTC, Emiyaaaaa approved these changes
LGTM

2022-11-15 03:51 UTC, merged