fix:修复全景指南针的展示问题
realsee-developer/dnalogel pull request #78
Opened 2022-08-09 11:12 UTC by sansi-lcj

2022-08-10 04:24 UTC, Flying-Snail requested changes

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
>      this.compassMesh?.material.map?.dispose()
销毁贴图时，最好还是直接销毁贴图吧，this.compassMesh?.material.map 这种都是很深层的引用了。THREE 的建议我看也是自己去管理和销毁公共贴图。

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.group.visible = this.state.visible
隐藏和展示是有动画的

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
> +      this.compassMesh.material.map?.dispose()
销毁模型和销毁贴图最好不要在一个地方，因为贴图可能存在共用关系。

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this._clearCompassIfNeed()
初始化的时候最好还是不要销毁之前的模型。因为大部分情况下，你的需求就只是更新了模型的透明度，或者更新了模型贴图，或者从场景中删除模型。这些操作都是可以通过单独的 API 去控制的。就跟更新 style 的时候没必要把 DOM 删了再新建一个一样。

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
>        '//vrlab-image4.ljcdn.com/release/web/v3/north-point-circle.96498e69.png'
这里是之前处理的时候没这个规范，现在的规范是，不要有网络资源加载。这个图片处理成 base64 吧。

2022-08-10 04:24 UTC, Flying-Snail commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.setState({
userAction 丢了

2022-08-10 10:09 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +interface Config {
確實非必填，改 constructor 裡進行default賦值

2022-08-10 10:39 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.state = Object.assign(this.state, state)
okk

2022-08-10 10:42 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +  public async load(data: PluginServerData | PluginData) {
简单粗暴记个todo

2022-08-10 10:43 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +      this.hooks.emit('enable', { userAction: options?.userAction || false })
okk

2022-08-10 10:43 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
>  import * as THREE from 'three'
搞掂

2022-08-10 10:43 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +  version: number
加上

2022-08-10 10:44 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +export type PanoCompassPluginParameterType = Config
已改

2022-08-10 10:44 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +      config,
已合并

2022-08-10 10:44 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.enable()
为了真初始化，已改

2022-08-10 10:44 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +        visible: true,
okk

2022-08-10 10:44 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +      userAction: options?.userAction || false,
已改

2022-08-10 10:48 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +  public async load(data: PluginServerData | PluginData) {
难受

2022-08-10 10:48 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +      this.init()
因为原先只有init做各种操作，我尽量不改这里面的逻辑。记todo拆分

2022-08-10 10:50 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
>      this.compassMesh?.material.map?.dispose()
记todo给原作者

2022-08-10 10:51 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +      this.compassMesh.material.map?.dispose()
这里简单的销毁后重新初始化

2022-08-10 10:52 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
>        '//vrlab-image4.ljcdn.com/release/web/v3/north-point-circle.96498e69.png'
保持逻辑不变，记todo

2022-08-10 10:54 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.setState({
加上加上

2022-08-10 10:54 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this.group.visible = this.state.visible
动画我就不处理了，给作者搞

2022-08-10 10:55 UTC, sansi-lcj commented on plugins/src/PanoCompassPlugin/controller.ts
> +    this._clearCompassIfNeed()
插件作者修改一个这个细分逻辑

2022-08-11 06:06 UTC, sansi-lcj reviewed
change

2022-08-11 06:29 UTC, Flying-Snail approved these changes

2022-08-11 06:55 UTC, merged